#
# Copyright (C) 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

resourcePackages:
- io.syndesis.server.endpoint.v1.handler.extension
- io.syndesis.server.endpoint.v1.handler.integration.support
- io.syndesis.server.endpoint.v1.handler.external
openAPI:
  info:
    title: Syndesis Supported API
    description: |
      The Syndesis Supported REST API connects to back-end services on
      the Syndesis and provides a single entry point for the 3rd party
      clients.
    version: v1-${project.version}
    contact:
      url: https://syndesis.io/
      email: syndesis@googlegroups.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
  servers:
  - url: http://localhost:8080
    description: Development server
    basePath:
      default: /api/v1